ARG ELK_VERSION=7.15.0

#https://www.docker.elastic.co/
FROM docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}

#WORKDIR /usr/share/elasticsearch/bin/
#RUN elasticsearch-certutil ca
#место для плагинов
#например: RUN elasticsearch-plugin install analysis-icu
