ARG ELK_VERSION=7.15.0

# https://www.docker.elastic.co/
FROM docker.elastic.co/logstash/logstash:${ELK_VERSION}

COPY ./config/logstash.yml /usr/share/logstash/config/
COPY ./pipeline/logstash.conf /usr/share/logstash/pipeline/

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
